/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JavaGameEngine;

import JavaGameEngine.jade.Window;

public class Main {
    public static void main(String[] args) {
        Window window = Window.get();
        window.run();
    }

    
}
